using System.Globalization;
using Microsoft.Extensions.Logging;

namespace Taskly.Data;

/// <summary>
/// 配置服务，对应原 Flutter 版 ConfigService。
/// 读写 ~/.taskly/config.ini（纯文本 INI 风格，key=value，支持 ; / # 注释）。
/// 兼容原版配置键名：last-db-path（旧 last_db_path）、language、last-selected-list-id。
/// </summary>
public sealed class ConfigService
{
    private readonly string _configPath;
    private readonly ILogger<ConfigService>? _logger;
    private Dictionary<string, string> _values = new(StringComparer.OrdinalIgnoreCase);

    public ConfigService(ILogger<ConfigService>? logger = null)
    {
        _configPath = PathUtils.GetConfigPath();
        _logger = logger;
    }

    /// <summary>从磁盘加载配置。文件不存在则使用空配置。</summary>
    public async Task LoadAsync()
    {
        _values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(_configPath))
        {
            return;
        }

        try
        {
            var lines = await File.ReadAllLinesAsync(_configPath);
            foreach (var raw in lines)
            {
                var line = raw.Trim();
                if (line.Length == 0 || line.StartsWith(';') || line.StartsWith('#'))
                {
                    continue;
                }

                var eq = line.IndexOf('=');
                if (eq <= 0)
                {
                    continue;
                }

                var key = line[..eq].Trim();
                var value = line[(eq + 1)..].Trim();
                _values[key] = value;
            }
        }
        catch (Exception ex)
        {
            _logger?.LogError(ex, "Failed to load config from {Path}", _configPath);
        }
    }

    /// <summary>持久化配置到磁盘。</summary>
    public async Task SaveAsync()
    {
        try
        {
            var dir = Path.GetDirectoryName(_configPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("# Taskly configuration");
            sb.AppendLine("# This file is automatically generated and managed by Taskly.");
            foreach (var kv in _values)
            {
                sb.Append(kv.Key).Append('=').AppendLine(kv.Value);
            }

            await File.WriteAllTextAsync(_configPath, sb.ToString());
        }
        catch (Exception ex)
        {
            _logger?.LogError(ex, "Failed to save config to {Path}", _configPath);
        }
    }

    /// <summary>读取配置值，不存在返回默认值。</summary>
    public string Get(string key, string defaultValue = "")
    {
        if (_values.TryGetValue(key, out var v))
        {
            return v;
        }

        // 兼容旧键名 last_db_path
        if (key == "last-db-path" && _values.TryGetValue("last_db_path", out var legacy))
        {
            return legacy;
        }

        return defaultValue;
    }

    public void Set(string key, string value) => _values[key] = value;

    /// <summary>上次打开的数据库路径。</summary>
    public string LastDbPath
    {
        get => Get("last-db-path", string.Empty);
        set => Set("last-db-path", value);
    }

    /// <summary>语言（zh / en），默认 zh。</summary>
    public string Language
    {
        get => Get("language", "zh");
        set => Set("language", value);
    }

    /// <summary>上次选中的列表 id（字符串存储，读取时解析）。</summary>
    public int LastSelectedListId
    {
        get => int.TryParse(Get("last-selected-list-id", "0"), CultureInfo.InvariantCulture, out var id) ? id : 0;
        set => Set("last-selected-list-id", value.ToString(CultureInfo.InvariantCulture));
    }
}
